name: VS Code Extension Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Semver release type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      releaseChannel:
        description: 'Release channel'
        required: true
        default: 'stable'
        type: choice
        options:
          - stable
          - edge
      publishMarketplace:
        description: 'Publish to VS Code Marketplace?'
        required: true
        default: 'yes'
        type: choice
        options:
          - yes
          - no
      publishOpenVSX:
        description: 'Publish to OpenVSX?'
        required: true
        default: 'yes'
        type: choice
        options:
          - yes
          - no
      additionalFlags:
        description: 'Additional VSCE flags (optional)'
        required: false
        default: ''

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (Development)
        if: ${{ github.event.inputs.releaseChannel == 'edge' }}
        run: npm run build:dev

      - name: Build (Production)
        if: ${{ github.event.inputs.releaseChannel == 'stable' }}
        run: npm run build:prod

      - name: Generate Changelog
        run: |
          git log $(git describe --tags --abbrev=0)..HEAD --oneline > CHANGELOG.md
          cat CHANGELOG.md

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Calculate Version
        id: version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if [ "${{ github.event.inputs.releaseChannel }}" == "edge" ]; then
            if [[ "$CURRENT_VERSION" != *"edge"* ]]; then
              NEW_VERSION=$(npx semver $CURRENT_VERSION -i pre${{ github.event.inputs.releaseType }} --preid edge)
            else
              NEW_VERSION=$(npx semver $CURRENT_VERSION -i prerelease)
            fi
          else
            NEW_VERSION=$(npx semver $CURRENT_VERSION -i ${{ github.event.inputs.releaseType }})
          fi
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "Using version: $NEW_VERSION"

      - name: Update Version
        run: |
          npm version $NEW_VERSION --no-git-tag-version
          git tag -a v$NEW_VERSION -m "Release v$NEW_VERSION"
          git add package.json package-lock.json

      - name: Package Extension
        run: |
          if [ "${{ github.event.inputs.releaseChannel }}" == "edge" ]; then
            node .github/scripts/updateEdgeVersion.js
            npx vsce package --pre-release -o extension-$NEW_VERSION.vsix ${{ github.event.inputs.additionalFlags }}
          else
            npx vsce package -o extension-$NEW_VERSION.vsix ${{ github.event.inputs.additionalFlags }}
          fi

      - name: Publish to VS Code Marketplace
        if: ${{ github.event.inputs.publishMarketplace == 'yes' }}
        run: |
          npx vsce publish --packagePath extension-$NEW_VERSION.vsix \
            --pre-release ${{ github.event.inputs.releaseChannel == 'edge' && '--pre-release' || '' }} \
            -p ${{ secrets.VS_MARKETPLACE_TOKEN }}

      - name: Publish to OpenVSX
        if: ${{ github.event.inputs.publishOpenVSX == 'yes' }}
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: extension-$NEW_VERSION.vsix
          preRelease: ${{ github.event.inputs.releaseChannel == 'edge' }}

      - name: Push Changes
        run: |
          git add package.json package-lock.json
          git commit -m "chore: bump version to $NEW_VERSION"
          git push origin HEAD:main --tags

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.NEW_VERSION }}
          artifacts: 'extension-*.vsix'
          bodyFile: CHANGELOG.md
          prerelease: ${{ github.event.inputs.releaseChannel == 'edge' }}