name: Build and Deploy Extension
on:
  push:
    tags:
      - 'v*'  
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      
      - name: Install Dependencies
        run: |
          pnpm prune
          pnpm install

      - name: Package Extension
        run: |
          pnpm add -g @vscode/vsce
          vsce package -o extension.vsix

      - name: Publish to Visual Studio Marketplace
        env:
          VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}
        run: vsce publish --pat $VSCE_PAT

      - name: Publish to Open VSX Registry
        env:
          OVSX_PAT: ${{ secrets.OPEN_VSX_TOKEN }}
        run: npx ovsx publish --pat $OVSX_PAT