name: Build and Deploy Extension

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup pnpm Global Bin Directory
        run: |
          pnpm setup
          export PNPM_HOME="${HOME}/.local/share/pnpm"
          echo "PNPM_HOME=${PNPM_HOME}" >> $GITHUB_ENV
          echo "${PNPM_HOME}/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: pnpm install

      - name: Package Extension
        run: |
          pnpm add -g @vscode/vsce
          vsce package

      - name: Publish to Visual Studio Marketplace
        env:
          VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}
        run: vsce publish --pat $VSCE_PAT

      - name: Publish to Open VSX Registry
        env:
          OVSX_PAT: ${{ secrets.OPEN_VSX_TOKEN }}
        run: npx ovsx publish --pat $OVSX_PAT
